<?php

namespace shihunguilai\phpapi\Cache;

use PHPUnit_Framework_TestCase;

class CacheRedisTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        if (!extension_loaded('redis')) {
            $this->markTestSkipped('no redis extension');
        }
    }

    public function testRedisExt()
    {
        $this->assertTrue(extension_loaded('redis'));
    }
    public function testGetInstance()
    {
        $a = CacheRedis::getInstance();
        $b = CacheRedis::getInstance();
        $this->assertEquals($a, $b);
    }
}
